### PR TITLE
Allow for proxy for mechanize

### PR DESCRIPTION
**Pull request by alex-go**
As requested with squashed commits.
allows the use for a http proxy with linkedin-scraper

### CODE REVIEW

**Comment by yatish27** [comment]
Can you send a PR with the latest Master

**Comment by cyberfab007** [comment]
Did this scraper ever work with the proxies ?

**Comment by chamnap** [comment]
@yatish27, why do you close this PR?

**Comment by cyberfab007** [comment]
I saw this ticlket closed is there a new commit with this working with proxies 
?

**Pull request closed without merging**
