### PR TITLE
Adds volunteering and recommendations to profile

### PR DESCRIPTION
**Pull request by rowanhogan**
- Updates fixture to latest version
- Updates specs

### CODE REVIEW

**Comment by rowanhogan** [comment]
Hi @yatish27,

Well arguably recommendations aren't that useful from the public version of a profile (it doesn't display the name of the person who made the recommendation) but the volunteering information is reasonably detailed.

I found this gem useful for a custom resume builder personal project I'm working on, and I believed my additions would benefit the original gem?

Wouldn't you want everything available on the page available in the data object?

**Comment by yatish27** [comment]
@rowanhogan I added the comment only for "description_html"

**Comment by rowanhogan** [comment]
Ah sorry @yatish27, I just saw the comment here in this thread. I added it because I didn't want to change the existing method (and potentially break other developers' codebases) which was removing newlines. I wanted to also have a version that preserved them, and in the case swapped them to `<br>` elements in HTML for easy consumption within a web app view.

Please let me know your thoughts, I'm happy to change if you can see a better way to have an option of preserving the newlines?

**Comment by rcavezza** [comment]
Is there anything I can do to help get this merged in? Perhaps pull down and fix the merge conflicts?

**Pull request closed without merging**
